name: Build for production to VPS
on:
  push:
    branches: ['main']
jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          NODE_OPTIONS="--max_old_space_size=4096" npm run build

      - name: Archive build folder
        run: |
          zip -r build.zip build/

      - name: Copy archive to deployment directory
        run: |
          rm -rf ~/projects/berlian-motor/*
          mkdir -p ~/projects/berlian-motor
          mv build.zip ~/projects/berlian-motor/

      - name: Extract build to target directory
        run: |
          unzip -o ~/projects/berlian-motor/build.zip -d ~/projects/berlian-motor/
          rm ~/projects/berlian-motor/build.zip
